src/Entity/Actor.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActorRepository")
 */
class Actor
{


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $actorid;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $text;


     /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $forename;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $surname;

  /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $specifier;


    /**
     * @ORM\Column(type="string", length="20",nullable=true)
     */
    private $birthdate;


    /**
     * @ORM\Column(type="string", length="20",nullable=true)
     */
    private $deathdate;




    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $contributor;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedt;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $keywords;


   //private $roles;


     public function __construct() {
        $this->roles = new ArrayCollection();
    }


    public function getActorid(): ?int
    {
        return $this->actorid;
    }

    public function setActorid(int $ref): self
    {
        $this->actorid= $ref;

        return $this;
    }





    public function getText(): ?string
    {
        return $this->text;
    }


    public function setText($text): self
    {
        $this->text = $text;

        return $this;
    }


    public function getForename(): ?string
    {
        return $this->forename;
    }


    public function setForename(string $name): self
    {
        $this->forename = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }


    public function getLabel(): ?string
    {
        return $this->surname.", ".$this->forename." (".$this->birthdate."-".$this->deathdate.")";
    }

    public function setSurname(string $name): self
    {
        $this->surname = $name;

        return $this;
    }

    public function getSpecifier(): ?string
    {
        return $this->specifier;
    }


    public function setSpecifier($name): self
    {
        $this->specifier = $name;

        return $this;
    }


    public function getDeathdate(): ?string
    {
        return $this->deathdate;
    }


    public function setDeathdate(string $text): self
    {
        $this->deathdate = $text;
        return $this;
    }



    public function getBirthdate(): ?string
    {
        return $this->birthdate;
    }


    public function setBirthdate(string $text): self
    {
        $this->birthdate = $text;
        return $this;
    }


    public function getContributor(): ?string
    {
        return $this->contributor;
    }

    public function setContributor(?string $contributor): self
    {
        $this->contributor = $contributor;

        return $this;
    }

    public function getUpdateDt(): ?\DateTimeInterface
    {
        return $this->updatedt;
    }



    public function setUpdateDt(?\DateTimeInterface $updatedt): self
    {
        $this->updatedt = $updatedt;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }


    public function setKeywords(string $name): self
    {
        $this->keywords = $name;

        return $this;
    }
}

src/Entity/Relation.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RelationRepository")
 */

class Relation
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $relationid;


    /**
     * @ORM\Column(type="integer")
     **/
    private $actor1ref;


    /**
     * @ORM\Column(type="text")
     **/
    private $relation;


    /**
     * @ORM\Column(type="integer")
     **/
    private $actor2ref;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $clues;


    public function getRelationId(): ?int
    {
        return $this->relationid;
    }

   public function setRelationiId(int $ref): self
    {
        $this->relationid= $ref;
        return $this;
    }

    public function getActor1Ref(): ?int
    {
        return $this->actor1ref;
    }

    public function setActor1Ref(int $ref): self
    {
        $this->actor1ref= $ref;
        return $this;
    }

    public function getActor2Ref(): ?int
    {
        return $this->actor2ref;
    }

    public function setActor2Ref(int $ref): self
    {
        $this->actor2ref= $ref;
        return $this;
    }

    public function getRelation(): ?string
    {
        return $this->relation;
    }

    public function setRelation(string $text): self
    {
        $this->relation = $text;
        return $this;
    }

    public function getClues(): ?string
    {
        return $this->clues;
    }


    public function setClues(string $text): self
    {
        $this->clues = $text;
        return $this;
    }

    public function setConfidence(int $num): self
    {
        $this->confidence= $num;
        return $this;
    }

    public function getConfidence(): int
    {
        return $this->confidence;
    }



}

src/Controller/RelationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

//use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RequestStack;
use App\Service\MyLibrary;

use App\Service\Templates;
use Symfony\Component\Yaml\Yaml;
use Doctrine\Persistence\ManagerRegistry;


use App\Entity\Actor;
use App\Entity\ActorRole;
use App\Entity\Role;
use App\Entity\Glimpse;
use App\Entity\Relation;
use App\Entity\RelationClue;
use App\Entity\LifeEvent;


use Symfony\Component\Config\FileLocator;

class RelationController extends AbstractController
{

    private $requestStack ;
    private $doctrine;

    //    private  $templatelist=array();
    //   private  $agelist=array();

    public function __construct(private ManagerRegistry $adoctrine, RequestStack $request_stack, string $templatedir)
    {

        // $ageyml = $templates->agelist; //fileLocator->locate('agelist3.yml', null, false);
        // $this->agelist =    $templates->agelist;
        $this->requestStack = $request_stack;
        $this->doctrine = $adoctrine;

    }

    public function showAll()
    {
        $relations = $this->doctrine->getRepository(Relation::class)->getAll();
        dump($relations);
        foreach($relations as &$relation)
        {
            $relation->{"actor1"}= $this->doctrine->getRepository(Actor::class)->findOne($relation->getActor1ref());
            $relation->{"actor2"}= $this->doctrine->getRepository(Actor::class)->findOne($relation->getActor2ref());
        }

        return $this->render(
            'relation/showall.html.twig',
            [
            'relations'=>$relations,
            'returnlink'=>"/actor/showall",
            ]
        );
    }



    public function showone(ManagerRegistry $doctrine,$rid)
    {
        $relation = $doctrine->getRepository(Relation::class)->getOne($rid);
        $actor1 = $doctrine->getRepository(Actor::class)->findOne($relation->getActor1ref());
        $actor2 = $doctrine->getRepository(Actor::class)->findOne($relation->getActor2ref());

        dump($actor1);
        dump($actor2);

        $clues = $doctrine->getRepository(RelationClue::class)->findClues($rid);
        $cluelist=array();
        foreach($clues as $clue)
        {
            $clue->{"glimpse"} =  $doctrine->getRepository(Glimpse::class)->findOne($clue->getGlimpseRef());
              $clue->{"glimpse"}->{"roles"} =  $doctrine->getRepository(Role::class)->findChildren($clue->getGlimpseRef());
            $cluelist[]=$clue->getGlimpseRef();
        }
        dump($clues);
        $allroles = $doctrine->getRepository(Role::class)->getRelationClues($actor1,$actor2);
        $glimpses = array();
        $roles = array();
        foreach($allroles as &$role)
        {
            if((!in_array($role->getGlimpseref(), $cluelist, true)))
            {
                $roles[$role->getGlimpseref()]=$role;
                $role->{"glimpse"}=$doctrine->getRepository(Glimpse::class)->findOne($role->getGlimpseref());
                $glimpses[$role->getGlimpseref()] =  $doctrine->getRepository(Glimpse::class)->findOne($role->getGlimpseref());
            }
        }
        dump($roles);
        return $this->render(
            'relation/show.html.twig',
            [
            'relation'=>$relation,
            'actor1'=>$actor1,
            'actor2'=>$actor2,
            'clues'=>$clues,
            'roles'=>$roles,
            'returnlink'=>"/relation/showall",
            ]
        );
    }

    public function addclue(ManagerRegistry $doctrine,$rid, $gref)
    {

        $aclue = new RelationClue();
        $aclue->setRelationRef($rid);
        $aclue->setGlimpseRef($gref);
        $entityManager = $doctrine->getManager();
        $entityManager->persist($aclue);
        $entityManager->flush();
        return $this->redirect("/relation/show/".$rid);
    }

    public function deleterole(ManagerRegistry $doctrine,$aid, $rid)
    {

        $em = $doctrine->getManager();
        $ar = $doctrine->getRepository(ActorRole::class)->findone($aid, $rid);
        $em->remove($ar);
        $em->flush();
        return $this->redirect("/actor/editroles/".$aid);
    }


}

templates/relation/show.html.twig
{# templates/relation/show.html.twig #}

{% extends 'base.html.twig' %}

{% block stylesheets %}
{{ parent() }}
<link href="{{ asset('css/relation.css') }}" rel="stylesheet" />
{% endblock %}

{% block js %}
{{ parent() }}

{% endblock %}

{% block body %}
<div id="relation" >
    <div class ="heading" >
        <div class="title">Relationship</div>
        <div class="returnbutton button1"> <a href = "/actor/showall" >return </a> </div>
    </div>
    <div class="subheading row" >
    <div class= "title">{{actor1.label}} {{relation.relation}} {{actor2.label}}</div>
</div>
<div ></div>
<div >
  <div class="actor">
        <div class="row">
           <div class="returnbutton"> <a href = "/actor/show/{{relation.actor1ref}}" >show </a> </div>
                <div class= "field"> {{actor1.label}}</div>
                <div class= "field">( {{actor1.specifier}} )</div>
            </div>
        </div>
  <div class="actor">
        <div class="row">
           <div class="returnbutton"> <a href = "/actor/show/{{relation.actor2ref}}" >show </a> </div>
                <div class= "field"> {{actor2.label}}</div>
                <div class= "field">( {{actor2.specifier}} )</div>
            </div>
        </div>
    </div>
    <div ></div>
      <div class="subheading" >
            <div class="title">Clues </div>
        </div>
{% dump  clues %}
            <div class="">
                {% for cid, clue in clues %}
                <div class="row">
                   <div class="returnbutton"> <a href = "/glimpse/show/{{clue.glimpseref}}" >View Glimpse </a></div>
                            <div class="cell">{{  FormatEvent(clue.glimpse)}}  </div>

   </div>
                    {% endfor %}
</div>

      <div class="subheading" >
            <div class="title">Roles </div>
        </div>
{% dump  roles %}
            <div class="list">
                {% for rid, role in roles %}
                <div class="row">
                   <div class="returnbutton"> <a href = "/glimpse/show/{{role.glimpse.glimpseid}}" >View Glimpse </a></div>

                         <div class="cell"> {{role.glimpse.location}}  </div>
                         <div class="cell"> {{role.glimpse.type}}  </div>
                           <div class="cell">{{role.glimpse.date}}  </div>
                         <div class="cell"> {{role.role}}  </div>
                         <div class="cell">{{role.name}}   </div>
                         <div class="cell">{{role.predicates}}   </div>
                          <div class="returnbutton"> <a href = "/relation/addclue/{{relation.relationid}}/{{role.glimpseref}}" >Add to clues </a></div>

   </div>
                    {% endfor %}
</div>

{% endblock %}

templates/relation/showall.html.twig
{# templates/relation/show.html.twig #}

{% extends 'base.html.twig' %}

{% block stylesheets %}
{{ parent() }}
<link href="{{ asset('css/relation.css') }}" rel="stylesheet" />
{% endblock %}

{% block js %}
{{ parent() }}

{% endblock %}

{% block body %}
<div id="relation" >


    <div class ="heading" >
      <div class="title">Relations</div></div>
        <div class="returnbutton button1"> <a href = "/actor/showall" >return </a> </div>
    </div>
    <div class="list" >


    {% for relation in relations %}

    <div class="row" >
     <div class="returnbutton"> <a href = "/relation/show/{{relation.relationid}}" >show </a> </div>
    <div>{{relation.actor1.label}} {{relation.relation}} {{relation.actor2.label}}</div>

    </div>
    {% endfor %}



    </div>
</div>

{% endblock %}